#include "../cpp/WindCore.hpp"
#include "../cpp/WindResources.hpp"
#include "../cpp/WindFade.hpp"
#include "../cpp/WindShaders.hpp"

#import <ImageIO/ImageIO.h>
#import <MapLibre/MapLibre.h>
#import <MetalKit/MetalKit.h>
#import <React/RCTViewManager.h>

#include <atomic>

#import <mach/mach.h>

static maris::TileCache tileCache;

static NSUInteger gfsSetGridCalls;
static CFTimeInterval gfsSetGridLastLog;

#pragma mark - GFS field identity

static NSString *MarisGfsFieldKey(NSDictionary *payload) {
  if (!payload) return nil;

  // Prefer an explicit stable key generated by JS/backend if available.
  for (NSString *candidateKey in @[
    @"fieldKey",
    @"cacheKey",
    @"key",
  ]) {
    id value = payload[candidateKey];

    if ([value isKindOfClass:NSString.class] &&
        ((NSString *)value).length > 0) {
      return value;
    }
  }

  NSArray *tiles = payload[@"tiles"];

  if (![tiles isKindOfClass:NSArray.class]) {
    return nil;
  }

  /*
   * IMPORTANT:
   *
   * Do NOT put `tiles` itself in stringWithFormat.
   *
   * `tiles` contains windU/windV arrays and converting the whole object to
   * NSString is extremely expensive.
   *
   * The fallback key contains only metadata.
   */
  NSMutableString *key = [NSMutableString stringWithFormat:
    @"%@|%@|%@|%@|%lu",
    payload[@"run"] ?: @"",
    payload[@"model"] ?: @"",
    payload[@"forecastTime"] ?: @"",
    payload[@"resolution"] ?: @"",
    (unsigned long)tiles.count
  ];

  for (NSDictionary *tile in tiles) {
    if (![tile isKindOfClass:NSDictionary.class]) {
      continue;
    }

    NSDictionary *bounds = tile[@"bounds"];

    id z = tile[@"z"] ?: @"";
    id x = tile[@"x"] ?: @"";
    id y = tile[@"y"] ?: @"";

    id width = tile[@"width"] ?: @0;
    id height = tile[@"height"] ?: @0;

    if ([bounds isKindOfClass:NSDictionary.class]) {
      [key appendFormat:
        @"|%@/%@/%@:%@,%@,%@,%@:%@x%@",
        z,
        x,
        y,
        bounds[@"west"] ?: @"",
        bounds[@"south"] ?: @"",
        bounds[@"east"] ?: @"",
        bounds[@"north"] ?: @"",
        width,
        height
      ];
    } else {
      [key appendFormat:
        @"|%@/%@/%@:%@x%@",
        z,
        x,
        y,
        width,
        height
      ];
    }
  }

  return key;
}

#pragma mark - Wind layer

@interface MarisWindLayer : MLNCustomStyleLayer

@property float particleOpacity;
@property float density;
@property float animationSpeed;
@property BOOL windVisible;

@property(copy) void (^dataStatus)(
  BOOL stale,
  double savedAt,
  BOOL loading
);

- (void)load:(maris::Plan)plan;
- (void)resetRequests;
- (int)resolutionPenalty;
- (int)maximumDimension;
- (BOOL)fadeFinished;
- (double)speedAtCenter:(CLLocationCoordinate2D)center;
- (void)setGfsField:(NSDictionary *)payload;

@end

@implementation MarisWindLayer {
  id<MTLDevice> _device;
  id<MTLRenderPipelineState> _trails;
  id<MTLDepthStencilState> _depth;

  std::shared_ptr<maris::Field> _oldField;
  maris::WindFade _fieldTransition;
  std::shared_ptr<maris::Field> _field;
  std::mutex _fieldMutex;

  maris::Particles _particles;

  std::vector<maris::ClipVertex> _trailMesh;

  maris::RenderStats _stats;

  BOOL _measure;

  NSString *_key;
  NSURLSession *_session;
  dispatch_queue_t _loader;

  std::atomic<NSUInteger> _generation;

  double _nextLoadAt;
  double _previous;
  double _dataSavedAt;

  BOOL _loading;

  maris::Quality _quality;
  maris::WindFade _fade;

  NSString *_snapshotPath;
  NSString *_catalogPath;

  NSString *_gfsKey;

  NSURLSessionDataTask *_activeTask;

  id<MTLBuffer> _buffers[3];

  NSUInteger _gpuVertexCount;
  int _gpuBufferSlot;

  std::shared_ptr<
    std::array<std::atomic_bool, 3>
  > _busy;
}

- (instancetype)initWithIdentifier:(NSString *)identifier {
  if ((self = [super initWithIdentifier:identifier])) {
    _generation.store(0);

    _gpuBufferSlot = -1;

    _measure =
      [NSProcessInfo.processInfo.environment[
        @"MARIS_WIND_METRICS"
      ] boolValue];

#if DEBUG
    _measure = YES;
#endif

    _particleOpacity = .65;
    _density = .6;
    _animationSpeed = 1;

    _quality = maris::Quality(
      NSProcessInfo.processInfo.physicalMemory <=
        3ULL * 1024 * 1024 * 1024 ||
      NSProcessInfo.processInfo.lowPowerModeEnabled
    );

    _busy =
      std::make_shared<
        std::array<std::atomic_bool, 3>
      >();

    for (auto &busy : *_busy) {
      busy.store(false);
    }

    static dispatch_queue_t loader;
    static dispatch_once_t once;

    dispatch_once(&once, ^{
      loader = dispatch_queue_create(
        "com.maris.wind.loader",
        DISPATCH_QUEUE_SERIAL
      );
    });

    _loader = loader;

    NSURL *directory =
      [[NSFileManager.defaultManager
        URLsForDirectory:NSApplicationSupportDirectory
        inDomains:NSUserDomainMask]
          .firstObject
        URLByAppendingPathComponent:@"maris-wind"
        isDirectory:YES];

    [NSFileManager.defaultManager
      createDirectoryAtURL:directory
      withIntermediateDirectories:YES
      attributes:nil
      error:nil];

    [directory
      setResourceValue:@YES
      forKey:NSURLIsExcludedFromBackupKey
      error:nil];

    _snapshotPath =
      [directory
        URLByAppendingPathComponent:@"last-field.bin"]
        .path;

    _catalogPath =
      [directory
        URLByAppendingPathComponent:@"last-catalog.json"]
        .path;

    NSURLSessionConfiguration *config =
      NSURLSessionConfiguration
        .defaultSessionConfiguration;

    config.HTTPAdditionalHeaders = @{
      @"User-Agent" :
        @"Maris/1.0 (https://github.com/andre-fig/maris)"
    };

    config.timeoutIntervalForRequest = 5;
    config.timeoutIntervalForResource = 5;

    config.URLCache =
      [[NSURLCache alloc]
        initWithMemoryCapacity:2 * 1024 * 1024
        diskCapacity:32 * 1024 * 1024
        diskPath:@"maris-wind"];

    _session =
      [NSURLSession
        sessionWithConfiguration:config];
  }

  return self;
}

- (void)didMoveToMapView:(MLNMapView *)map {
  MLNBackendResource *r =
    map.backendResource;

  _device = r.device;

  NSError *error = nil;

  auto source = maris::metalShader();

  id<MTLLibrary> lib =
    [_device
      newLibraryWithSource:@(source.c_str())
      options:nil
      error:&error];

  if (!lib) {
    NSLog(
      @"[Wind] Metal shader error: %@",
      error
    );

    return;
  }

  MTLRenderPipelineDescriptor *d =
    [MTLRenderPipelineDescriptor new];

  d.vertexFunction =
    [lib newFunctionWithName:@"windVertex"];

  d.fragmentFunction =
    [lib newFunctionWithName:@"particleFragment"];

  d.colorAttachments[0].pixelFormat =
    r.mtkView.colorPixelFormat;

  d.depthAttachmentPixelFormat =
    MTLPixelFormatDepth32Float_Stencil8;

  d.stencilAttachmentPixelFormat =
    MTLPixelFormatDepth32Float_Stencil8;

  d.rasterSampleCount =
    r.mtkView.sampleCount;

  auto c =
    d.colorAttachments[0];

  c.blendingEnabled = YES;

  c.sourceRGBBlendFactor =
    MTLBlendFactorOne;

  c.destinationRGBBlendFactor =
    MTLBlendFactorOneMinusSourceAlpha;

  c.sourceAlphaBlendFactor =
    MTLBlendFactorOne;

  c.destinationAlphaBlendFactor =
    MTLBlendFactorOneMinusSourceAlpha;

  _trails =
    [_device
      newRenderPipelineStateWithDescriptor:d
      error:&error];

  if (!_trails) {
    NSLog(
      @"[Wind] Metal pipeline error: %@",
      error
    );
  }

  MTLDepthStencilDescriptor *depth =
    [MTLDepthStencilDescriptor new];

  depth.depthCompareFunction =
    MTLCompareFunctionAlways;

  depth.depthWriteEnabled = NO;

  _depth =
    [_device
      newDepthStencilStateWithDescriptor:depth];
}

- (double)speedAtCenter:
    (CLLocationCoordinate2D)center {
  std::lock_guard<std::mutex> lock(_fieldMutex);
  return maris::speedAtCoordinate(
    _field.get(),
    center.longitude,
    center.latitude
  );
}

#pragma mark - GFS field

- (void)setGfsField:(NSDictionary *)payload {
  if (!payload) {
    std::lock_guard<std::mutex> lock(_fieldMutex);
    if (_gfsKey == nil && !_field) {
      return;
    }

    _gfsKey = nil;

    _oldField.reset();
    _field.reset();

    _particles =
      maris::Particles();

    _trailMesh.clear();

    _gpuVertexCount = 0;
    _gpuBufferSlot = -1;

    return;
  }

  NSArray *tiles =
    payload[@"tiles"];

  if (![tiles isKindOfClass:NSArray.class] ||
      tiles.count == 0) {
    return;
  }

  /*
   * Generate identity only from metadata.
   *
   * Never stringify windU/windV here.
   */
  NSString *key =
    MarisGfsFieldKey(payload);

  BOOL sameField = NO;
  {
    std::lock_guard<std::mutex> lock(_fieldMutex);
    sameField = key &&
      [key isEqualToString:_gfsKey] &&
      _field;
  }

  std::vector<maris::GridTile>
    nativeTiles;

  nativeTiles.reserve(tiles.count);

  for (NSDictionary *tile in tiles) {
    if (![tile
          isKindOfClass:NSDictionary.class]) {
      continue;
    }

    NSDictionary *bounds =
      tile[@"bounds"];

    NSArray *uValues =
      tile[@"windU"];

    NSArray *vValues =
      tile[@"windV"];

    NSInteger width =
      [tile[@"width"] integerValue];

    NSInteger height =
      [tile[@"height"] integerValue];

    const NSInteger cellCount =
      width * height;

    if (![bounds
          isKindOfClass:NSDictionary.class] ||
        ![uValues
          isKindOfClass:NSArray.class] ||
        ![vValues
          isKindOfClass:NSArray.class] ||
        width <= 0 ||
        height <= 0 ||
        uValues.count !=
          (NSUInteger)cellCount ||
        vValues.count !=
          (NSUInteger)cellCount) {
      continue;
    }

    std::vector<float> u(
      size_t(cellCount),
      0.f
    );

    std::vector<float> v(
      size_t(cellCount),
      0.f
    );

    std::vector<uint8_t> valid(
      size_t(cellCount),
      1
    );

    for (NSInteger i = 0;
         i < cellCount;
         ++i) {
      NSNumber *un = uValues[i];
      NSNumber *vn = vValues[i];

      if (![un
            isKindOfClass:NSNumber.class] ||
          ![vn
            isKindOfClass:NSNumber.class] ||
          !std::isfinite(
            un.doubleValue
          ) ||
          !std::isfinite(
            vn.doubleValue
          )) {
        valid[size_t(i)] = 0;
        continue;
      }

      u[size_t(i)] =
        un.floatValue;

      v[size_t(i)] =
        vn.floatValue;
    }

    maris::GridTile nativeTile{
        [bounds[@"west"]
          doubleValue],

        [bounds[@"south"]
          doubleValue],

        [bounds[@"east"]
          doubleValue],

        [bounds[@"north"]
          doubleValue],

        int(width),
        int(height),

        std::move(u),
        std::move(v),
        std::move(valid)
    };
    nativeTile.z = [tile[@"z"] intValue];
    nativeTile.x = [tile[@"x"] intValue];
    nativeTile.y = [tile[@"y"] intValue];
    nativeTiles.push_back(std::move(nativeTile));
  }

  if (nativeTiles.empty()) {
    return;
  }

  if (sameField) {
    std::lock_guard<std::mutex> lock(_fieldMutex);
    if (!_field || !key || ![key isEqualToString:_gfsKey]) return;
    for (auto &tile : nativeTiles) {
      _field->upsertGridTile(std::move(tile));
    }
    _loading = NO;
    [self setNeedsDisplay];
    return;
  }

  auto next =
    std::make_shared<maris::Field>(
      std::move(nativeTiles)
    );

  /*
   * Only commit the key once we know that the
   * payload produced a valid native field.
   */
  {
    std::lock_guard<std::mutex> lock(_fieldMutex);
    _gfsKey = [key copy];
    _oldField = _field;
    _fieldTransition = maris::WindFade();
    _field = std::move(next);
  }

  _particles.invalidateTrails();

  gfsSetGridCalls += 1;

  const CFTimeInterval now =
    CACurrentMediaTime();

  if (gfsSetGridLastLog == 0) {
    gfsSetGridLastLog = now;
  }

  if (now -
        gfsSetGridLastLog >= 1.0) {
    NSLog(
      @"[MarisWindPerf] nativeSetGridPerSecond=%lu",
      (unsigned long)gfsSetGridCalls
    );

    gfsSetGridCalls = 0;
    gfsSetGridLastLog = now;
  }

  _loading = NO;

  _nextLoadAt =
    CACurrentMediaTime() + 60;

  if (self.dataStatus) {
    self.dataStatus(
      NO,
      NSDate.date
        .timeIntervalSince1970,
      NO
    );
  }

  [self setNeedsDisplay];
}

#pragma mark - Legacy network

- (NSData *)fetch:(NSString *)url
        cacheOnly:(BOOL)cacheOnly {
  dispatch_semaphore_t done =
    dispatch_semaphore_create(0);

  __block NSData *result = nil;

  NSMutableURLRequest *request =
    [NSMutableURLRequest
      requestWithURL:
        [NSURL URLWithString:url]];

  request.cachePolicy =
    cacheOnly
      ? NSURLRequestReturnCacheDataDontLoad
      : NSURLRequestUseProtocolCachePolicy;

  NSURLSessionDataTask *task =
    [_session
      dataTaskWithRequest:request
      completionHandler:^(
        NSData *data,
        NSURLResponse *response,
        NSError *error
      ) {
        if (!error &&
            [(NSHTTPURLResponse *)response
              statusCode] == 200) {
          result = data;
        }

        dispatch_semaphore_signal(done);
      }];

  @synchronized(self) {
    _activeTask = task;
  }

  [task resume];

  dispatch_semaphore_wait(
    done,
    DISPATCH_TIME_FOREVER
  );

  @synchronized(self) {
    if (_activeTask == task) {
      _activeTask = nil;
    }
  }

  return result;
}

- (NSData *)fetch:(NSString *)url {
  return [self
    fetch:url
    cacheOnly:NO];
}

- (void)cancelActiveRequest {
  @synchronized(self) {
    [_activeTask cancel];
    _activeTask = nil;
  }
}

- (void)resetRequests {
  ++_generation;

  [self cancelActiveRequest];

  _key = nil;
  _loading = NO;
  _nextLoadAt = 0;
}

- (void)load:(maris::Plan)p {
  /*
   * Disabled.
   *
   * React Native GFS client owns:
   *
   * - acquisition
   * - cache
   * - coverage
   * - resident vector field
   *
   * Native does not fetch MET Norway.
   */
  return;
}

#pragma mark - Draw

- (void)drawInMapView:
    (MLNMapView *)map
          withContext:
    (MLNStyleLayerDrawingContext)context {
  if (!self.renderEncoder) {
    return;
  }

  _stats.begin();

  std::shared_ptr<maris::Field> f;
  std::shared_ptr<maris::Field> oldField;
  float progress = 1;
  {
    std::lock_guard<std::mutex> lock(_fieldMutex);
    f = _field;
    if (_oldField) {
      progress = _fieldTransition.update(true, CACurrentMediaTime());
      if (progress >= 1) _oldField.reset();
      oldField = _oldField;
    }
  }
  if (!f) return;

  const double *matrix =
    &context.projectionMatrix.m00;

  id<MTLRenderCommandEncoder>
    encoder =
      self.renderEncoder;

  [encoder
    setCullMode:
      MTLCullModeNone];

  [encoder
    setDepthStencilState:
      _depth];

  float fade =
    _fade.update(
      _windVisible,
      CACurrentMediaTime()
    );

  double now =
    CACurrentMediaTime();

  double delta =
    _previous
      ? now - _previous
      : 0;

  double dt =
    std::min(
      .05,
      delta
    );

  _previous = now;

  _quality.frame(delta);

  const auto &lines =
    _particles.update(
      *f,
      matrix,
      context.zoomLevel,
      dt,
      _density *
        _quality.density,
      _animationSpeed,
      oldField.get(),
      progress
    );

  if (_trails &&
      _particles
        .needsMeshRebuild()) {
    CGSize size =
      map.backendResource
        .mtkView
        .drawableSize;

    maris::buildTrailMesh(
      lines,
      size.width,
      size.height,
      _trailMesh
    );

    if (_trailMesh.empty()) {
      _gpuVertexCount = 0;
      _gpuBufferSlot = -1;

      _particles
        .markMeshUploaded();
    }

    if (!_trailMesh.empty()) {
      int slot = -1;

      for (int i = 0;
           i < 3;
           ++i) {
        bool available = false;

        if ((*_busy)[i]
              .compare_exchange_strong(
                available,
                true
              )) {
          slot = i;
          break;
        }
      }

      /*
       * Never block renderer waiting for GPU.
       * If all three buffers are busy,
       * retain the currently uploaded mesh.
       */
      if (slot >= 0) {
        NSUInteger bytes =
          _trailMesh.size() *
          sizeof(
            maris::ClipVertex
          );

        if (!_buffers[slot] ||
            _buffers[slot]
              .length < bytes) {
          _buffers[slot] =
            [_device
              newBufferWithLength:
                bytes
              options:
                MTLResourceStorageModeShared];
        }

        id<MTLBuffer> buffer =
          _buffers[slot];

        if (buffer) {
          memcpy(
            buffer.contents,
            _trailMesh.data(),
            bytes
          );

          auto busy =
            _busy;

          [map.backendResource
            .commandBuffer
            addCompletedHandler:^(
              id<MTLCommandBuffer>
                command
            ) {
              (*busy)[slot]
                .store(false);
            }];

          _gpuVertexCount =
            _trailMesh.size();

          _gpuBufferSlot =
            slot;

          _particles
            .markMeshUploaded();
        } else {
          (*_busy)[slot]
            .store(false);
        }
      }
    }
  }

  if (_trails &&
      _gpuVertexCount > 0) {
    id<MTLBuffer> buffer =
      _gpuBufferSlot >= 0
        ? _buffers[
            _gpuBufferSlot
          ]
        : nil;

    if (buffer) {
      float particleOpacity =
        _particleOpacity *
        fade;

      [encoder
        setFragmentBytes:
          &particleOpacity
        length:
          sizeof(
            particleOpacity
          )
        atIndex:0];

      [encoder
        setRenderPipelineState:
          _trails];

      [encoder
        setVertexBuffer:
          buffer
        offset:0
        atIndex:0];

      [encoder
        drawPrimitives:
          MTLPrimitiveTypeTriangle
        vertexStart:0
        vertexCount:
          _gpuVertexCount];
    }
  }

  if (_measure &&
      _stats.end()) {
    const auto lookupMetrics =
      f->consumeLookupMetrics();

    task_vm_info_data_t memory{};

    mach_msg_type_number_t count =
      TASK_VM_INFO_COUNT;

    task_info(
      mach_task_self(),
      TASK_VM_INFO,
      (task_info_t)&memory,
      &count
    );

    NSLog(
      @"[Wind] render callbacks=%.1f/s "
       "cpu=%.3fms "
       "atlasBytes=%zu "
       "vertices=%zu "
       "processFootprintMiB=%.1f "
       "samples/frame=%.1f "
       "directLookups=%llu "
       "avgTileLookupMs=%.4f",

      _stats.fps,
      _stats.averageCpuMs,

      f->rgba.size(),

      _gpuVertexCount,

      memory.phys_footprint /
        1048576.,

      lookupMetrics.samples /
        std::max(
          1.,
          _stats.fps * 5.
        ),

      (unsigned long long)
        lookupMetrics
          .directLookups,

      lookupMetrics
        .timedLookups
          ? (
              double(
                lookupMetrics
                  .lookupNanos
              ) /
              lookupMetrics
                .timedLookups
            ) /
              1e6
          : 0.0
    );
  }
}

- (int)resolutionPenalty {
  return _quality.zoomPenalty();
}

- (BOOL)fadeFinished {
  return !_field ||
    _fade.value <= 0;
}

- (int)maximumDimension {
  return _quality.maxDimension();
}

#pragma mark - Cleanup

- (void)willMoveFromMapView:
    (MLNMapView *)map {
  ++_generation;

  [self cancelActiveRequest];

  _key = nil;
  _gfsKey = nil;

  _oldField.reset();
  _field.reset();

  _trails = nil;
  _depth = nil;

  _gpuVertexCount = 0;
  _gpuBufferSlot = -1;

  _previous = 0;

  _fade =
    maris::WindFade();

  _particles =
    maris::Particles();

  std::vector<
    maris::ClipVertex
  >().swap(
    _trailMesh
  );

  for (int i = 0;
       i < 3;
       ++i) {
    _buffers[i] = nil;
  }

  [_session
    getAllTasksWithCompletionHandler:^(
      NSArray<NSURLSessionTask *>
        *tasks
    ) {
      for (NSURLSessionTask *task
           in tasks) {
        [task cancel];
      }
    }];
}

- (void)dealloc {
  [_session
    invalidateAndCancel];
}

@end

#pragma mark - Find MapLibre map

static MLNMapView *
findMap(UIView *view) {
  if ([view
        isKindOfClass:
          MLNMapView.class]) {
    return
      (MLNMapView *)view;
  }

  for (UIView *child
       in view.subviews) {
    MLNMapView *map =
      findMap(child);

    if (map) {
      return map;
    }
  }

  return nil;
}

#pragma mark - React Native control

@interface MarisWindControl : UIView

@property BOOL enabled;
@property float opacity;
@property float density;
@property float animationSpeed;

@property(nonatomic, copy)
  RCTDirectEventBlock
    onDataStatus;

@property(nonatomic, copy)
  RCTDirectEventBlock
    onCenterWind;

@property(nonatomic, copy)
  NSArray<NSNumber *>
    *sampleCoordinate;

@property(nonatomic, copy)
  NSDictionary
    *windField;

- (void)emitSample;

@end

@implementation MarisWindControl {
  __weak MLNMapView *_map;

  MarisWindLayer *_layer;

  // The React prop is incremental: after the first payload, subsequent
  // payloads may contain only newly loaded tiles. Keep the complete resident
  // set so a MapLibre style reload can recreate the layer without losing it.
  NSMutableDictionary<NSString *, NSDictionary *> *_windFieldTiles;
  NSString *_windFieldIdentity;
  NSDictionary *_windFieldMetadata;

  CADisplayLink *_clock;

  double _check;

  BOOL _validationApplied;
  double _validationAfter;
}

- (instancetype)init {
  if ((self = [super init])) {
    _opacity = .65;
    _density = .6;
    _animationSpeed = 1;

    _windFieldTiles = [NSMutableDictionary dictionary];

    self.userInteractionEnabled =
      NO;

    [NSNotificationCenter
      .defaultCenter
      addObserver:self
      selector:@selector(background)
      name:
        UIApplicationDidEnterBackgroundNotification
      object:nil];

    [NSNotificationCenter
      .defaultCenter
      addObserver:self
      selector:@selector(foreground)
      name:
        UIApplicationDidBecomeActiveNotification
      object:nil];

    [NSNotificationCenter
      .defaultCenter
      addObserver:self
      selector:@selector(memoryWarning)
      name:
        UIApplicationDidReceiveMemoryWarningNotification
      object:nil];
  }

  return self;
}

- (NSString *)fieldIdentityForPayload:(NSDictionary *)payload {
  if (!payload) return nil;

  NSString *explicitKey = payload[@"fieldKey"];
  if ([explicitKey isKindOfClass:NSString.class] && explicitKey.length > 0) {
    return explicitKey;
  }

  return [NSString stringWithFormat:@"%@|%@|%@|%@|%@",
    payload[@"run"] ?: @"",
    payload[@"model"] ?: @"",
    payload[@"forecastTime"] ?: @"",
    payload[@"sourceZoom"] ?: @"",
    payload[@"resolution"] ?: @""];
}

- (NSDictionary *)completeWindFieldPayload {
  if (!_windFieldMetadata || _windFieldTiles.count == 0) {
    return _windField;
  }

  NSMutableDictionary *payload = [_windFieldMetadata mutableCopy];
  payload[@"tiles"] = _windFieldTiles.allValues;
  return payload;
}

#pragma mark - Layer setup

- (void)configureLayer:
    (MarisWindLayer *)layer {
  __weak MarisWindControl *weak =
    self;

  layer.dataStatus =
    ^(
      BOOL stale,
      double savedAt,
      BOOL loading
    ) {
      MarisWindControl *owner =
        weak;

      if (!owner) {
        return;
      }

      [owner emitSample];

      if (owner.onDataStatus) {
        owner.onDataStatus(@{
          @"stale" :
            @(stale),

          @"savedAt" :
            @(savedAt * 1000),

          @"loading" :
            @(loading)
        });
      }
    };
}

- (void)createLayerIfNeeded {
  // Changing mapStyle replaces the MapLibre style object. The old custom
  // layer may still exist as an Objective-C object, but it is no longer part
  // of the current style and must not be reused.
  if (_layer && _map.style && _layer.style != _map.style) {
    if (_layer.style) {
      [_layer.style removeLayer:_layer];
    }
    _layer = nil;
  }

  if (_layer.style) {
    return;
  }

  _layer =
    [[MarisWindLayer alloc]
      initWithIdentifier:
        @"maris-native-wind"];

  [self
    configureLayer:_layer];

  /*
   * Configure current lightweight properties
   * once before first draw.
   */
  _layer.particleOpacity =
    _opacity;

  _layer.density =
    _density;

  _layer.animationSpeed =
    _animationSpeed;

  _layer.windVisible =
    _enabled;

  [_map.style
    addLayer:_layer];

  /*
   * IMPORTANT:
   *
   * Apply the GFS payload exactly once when
   * the layer is created.
   *
   * It is NOT reapplied every CADisplayLink tick.
   */
  if (_windField) {
    [_layer
      setGfsField:[self completeWindFieldPayload]];
  }
}

#pragma mark - App lifecycle

- (void)background {
  _clock.paused = YES;

  if (_layer.style) {
    [_layer.style
      removeLayer:_layer];
  }

  _layer = nil;

  tileCache.clear();
}

- (void)foreground {
  _clock.paused = NO;
}

- (void)memoryWarning {
  [self background];
  [self foreground];
}

- (void)dealloc {
  [NSNotificationCenter
    .defaultCenter
    removeObserver:self];

  [_clock invalidate];
}

- (void)didMoveToWindow {
  [super didMoveToWindow];

  [_clock invalidate];
  _clock = nil;

  if (self.window) {
    _clock =
      [CADisplayLink
        displayLinkWithTarget:self
        selector:@selector(tick:)];

    /*
     * Intentional production cap.
     *
     * Wind particles do not need to run at
     * 120 Hz to keep the rest of the app
     * responsive on ProMotion displays.
     */
    _clock.preferredFramesPerSecond =
      60;

    [_clock
      addToRunLoop:
        NSRunLoop.mainRunLoop
      forMode:
        NSRunLoopCommonModes];
  } else {
    if (_layer.style) {
      [_layer.style
        removeLayer:_layer];
    }

    _layer = nil;
    _map = nil;
  }
}

#pragma mark - React props

- (void)setSampleCoordinate:
    (NSArray<NSNumber *> *)coordinate {
  _sampleCoordinate =
    [coordinate copy];

  [self emitSample];
}

- (void)setWindField:
    (NSDictionary *)windField {
  /*
   * This setter is the ONLY normal path
   * that updates an existing layer's field.
   *
   * React calls this when the actual prop changes.
   *
   * Do not perform this work from tick:.
   */
  if (!windField) {
    _windField = nil;
    _windFieldMetadata = nil;
    _windFieldIdentity = nil;
    [_windFieldTiles removeAllObjects];
  } else {
    NSString *identity = [self fieldIdentityForPayload:windField];
    if (_windFieldIdentity && ![_windFieldIdentity isEqualToString:identity]) {
      [_windFieldTiles removeAllObjects];
    }

    _windFieldIdentity = [identity copy];
    _windField = [windField copy];
    NSMutableDictionary *metadata = [windField mutableCopy];
    [metadata removeObjectForKey:@"tiles"];
    _windFieldMetadata = [metadata copy];

    NSArray *tiles = windField[@"tiles"];
    if ([tiles isKindOfClass:NSArray.class]) {
      for (NSDictionary *tile in tiles) {
        if (![tile isKindOfClass:NSDictionary.class]) continue;
        NSString *tileKey = [NSString stringWithFormat:@"%@/%@/%@",
          tile[@"z"] ?: @0,
          tile[@"x"] ?: @0,
          tile[@"y"] ?: @0];
        _windFieldTiles[tileKey] = [tile copy];
      }
    }
  }

  if (_layer) {
    [_layer
      setGfsField:_windField];
  }

  [self emitSample];
}

- (void)setEnabled:
    (BOOL)enabled {
  if (enabled &&
      !_enabled) {
    [_layer resetRequests];
  }

  _enabled = enabled;

  if (_layer) {
    _layer.windVisible =
      enabled;
  }
}

- (void)setOpacity:
    (float)opacity {
  _opacity = opacity;

  if (_layer) {
    _layer.particleOpacity =
      opacity;
  }
}

- (void)setDensity:
    (float)density {
  _density = density;

  if (_layer) {
    _layer.density =
      density;
  }
}

- (void)setAnimationSpeed:
    (float)animationSpeed {
  _animationSpeed =
    animationSpeed;

  if (_layer) {
    _layer.animationSpeed =
      animationSpeed;
  }
}

#pragma mark - Sampling

- (void)emitSample {
  if (_sampleCoordinate.count != 2 ||
      !_onCenterWind) {
    return;
  }

  double speed =
    _layer
      ? [_layer
          speedAtCenter:
            CLLocationCoordinate2DMake(
              _sampleCoordinate[1]
                .doubleValue,

              _sampleCoordinate[0]
                .doubleValue
            )]
      : -1;

  _onCenterWind(@{
    @"speed" :
      speed < 0
        ? (id)NSNull.null
        : @(speed),

    @"coordinate" :
      _sampleCoordinate
  });
}

#pragma mark - Display link

- (void)tick:
    (CADisplayLink *)clock {
  if (UIApplication
        .sharedApplication
        .applicationState !=
      UIApplicationStateActive) {
    /*
     * Control Center can temporarily make
     * iOS inactive.
     *
     * Keep resident field intact.
     */
    return;
  }

  if (!_enabled) {
    if (_layer) {
      _layer.windVisible =
        NO;

      if ([_layer
            fadeFinished]) {
        if (_layer.style) {
          [_layer.style
            removeLayer:_layer];
        }

        _layer = nil;
      } else {
        [_layer
          setNeedsDisplay];
      }
    }

    return;
  }

  if (!_map) {
    for (UIView *parent =
           self.superview;
         parent && !_map;
         parent =
           parent.superview) {
      _map =
        findMap(parent);
    }
  }

  if (!_map.style) {
    return;
  }

#if DEBUG
  /*
   * Explicit opt-in test fixture.
   * Never modifies the camera in normal launches.
   */
  if (!_validationAfter) {
    _validationAfter =
      CACurrentMediaTime() + 2;
  }

  if (!_validationApplied &&
      CACurrentMediaTime() >
        _validationAfter) {
    _validationApplied =
      YES;

    NSArray *v =
      [NSProcessInfo
        .processInfo
        .environment[
          @"MARIS_WIND_CAMERA"
        ]
        componentsSeparatedByString:
          @","];

    if (v.count == 5) {
      [_map
        setCenterCoordinate:
          CLLocationCoordinate2DMake(
            [v[1] doubleValue],
            [v[0] doubleValue]
          )
        zoomLevel:
          [v[2] doubleValue]
        direction:
          [v[3] doubleValue]
        animated:NO];

      MLNMapCamera *camera =
        _map.camera;

      camera.pitch =
        [v[4] doubleValue];

      [_map
        setCamera:camera
        animated:NO];
    }
  }
#endif

  /*
   * Create/configure only when necessary.
   *
   * No layer removal/re-add on every tick.
   */
  [self createLayerIfNeeded];

  /*
   * These assignments are cheap scalars,
   * but setters already keep them synchronized.
   *
   * Keeping only windVisible here is enough
   * to drive fade state.
   */
  _layer.windVisible =
    YES;

  /*
   * IMPORTANT:
   *
   * DO NOT:
   *
   *   [_layer setGfsField:_windField];
   *
   * here.
   *
   * That used to run 60x/s on the main thread.
   */

  /*
   * Also DO NOT recreate dataStatus block here.
   *
   * It was configured once in configureLayer:.
   */

  [_layer
    setNeedsDisplay];
}

@end

#pragma mark - React Native manager

@interface MarisWindControlManager :
  RCTViewManager
@end

@implementation MarisWindControlManager

RCT_EXPORT_MODULE(
  MarisWindControl
)

- (UIView *)view {
  return
    [MarisWindControl new];
}

RCT_EXPORT_VIEW_PROPERTY(
  enabled,
  BOOL
)

RCT_EXPORT_VIEW_PROPERTY(
  opacity,
  float
)

RCT_EXPORT_VIEW_PROPERTY(
  density,
  float
)

RCT_EXPORT_VIEW_PROPERTY(
  animationSpeed,
  float
)

RCT_EXPORT_VIEW_PROPERTY(
  onDataStatus,
  RCTDirectEventBlock
)

RCT_EXPORT_VIEW_PROPERTY(
  onCenterWind,
  RCTDirectEventBlock
)

RCT_EXPORT_VIEW_PROPERTY(
  sampleCoordinate,
  NSArray
)

RCT_EXPORT_VIEW_PROPERTY(
  windField,
  NSDictionary
)

@end
